name: Release Pipeline

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  lint:
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 0

      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - uses: bahmutov/npm-install@v1

      - name: Lint
        run: make lint

  compile:
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 0

      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - uses: bahmutov/npm-install@v1

      - name: Compile
        run: make compile

      - uses: actions/upload-artifact@v2
        with:
          retention-days: 3
          name: compiled-libs
          path: |
            integration/*/lib/**/*
            packages/*/lib/**/*
            package.json

  test:
    needs:
      - lint
      - compile

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        node-version: [ 10.x, 12.x, 14.x ]
      fail-fast: false
      max-parallel: 6

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 0

      - name: Update Chrome
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get --only-upgrade install google-chrome-stable
          google-chrome --version

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - uses: bahmutov/npm-install@v1

      - name: Download compiled libs
        uses: actions/download-artifact@v2
        with:
          name: compiled-libs

      - name: Test
        run: make test

      - uses: actions/upload-artifact@v2
        if: matrix.os == 'ubuntu-latest' && matrix.node-version == '14.x'
        with:
          retention-days: 3
          name: test-reports
          path: |
            target/**/*
            package.json

  integration-test:
    needs:
      - lint
      - compile

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        node-version: [ 10.x, 12.x, 14.x ]
      fail-fast: false
      max-parallel: 6

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 0

      - name: Update Chrome
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get --only-upgrade install google-chrome-stable
          google-chrome --version

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - uses: bahmutov/npm-install@v1

      - name: Download compiled libs
        uses: actions/download-artifact@v2
        with:
          name: compiled-libs

      - name: Integration Test
        run: make integration-test

  report:
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 0
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - uses: bahmutov/npm-install@v1

      - name: Download code coverage reports
        uses: actions/download-artifact@v2
        with:
          name: test-reports

      - name: Merge code coverage reports
        run: make report

      - name: Publish coverage
        if: github.ref == 'refs/heads/master'
        run: npm run coverage:publish
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

  release:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs:
      - test
      - integration-test
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 0
      - uses: ./.github/actions/setup-lerna
        with:
          github_token:   ${{ secrets.GH_TOKEN }}
          git_user_email: ${{ secrets.RELEASE_GH_EMAIL }}
          git_username:   ${{ secrets.RELEASE_GH_USERNAME }}
          npm_token:      ${{ secrets.NPM_TOKEN }}
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - uses: bahmutov/npm-install@v1

      - name: Download compiled libs
        uses: actions/download-artifact@v2
        with:
          name: compiled-libs

      - name: Publish artifacts
        run: npm run lerna:publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - uses: actions/upload-artifact@v2
        with:
          retention-days: 3
          name: changelog
          path: |
            CHANGELOG.md

  site:
    runs-on: ubuntu-latest
    needs:
      - release
    if: always()

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 0
      - uses: ./.github/actions/setup-lerna
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          git_user_email: ${{ secrets.RELEASE_GH_EMAIL }}
          git_username: ${{ secrets.RELEASE_GH_USERNAME }}
          npm_token: ${{ secrets.NPM_TOKEN }}
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - uses: bahmutov/npm-install@v1

      - name: Download changelog
        if: needs.release.result == 'success'
        uses: actions/download-artifact@v2
        with:
          name: changelog

      - name: Build Serenity/JS website
        run: make site

      - name: Publish website
        if: github.ref == 'refs/heads/master'
        run: npm run site:publish
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
